// <auto-generated />
using System;
using HotelCalcApp.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelCalcApp.Migrations
{
    [DbContext(typeof(HotelCalcAppDBContext))]
    partial class HotelCalcAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HotelCalcApp.Model.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameHotel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.HotelService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HotelServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdHotel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelServices");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.HotelServicePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateActualPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEndPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStartPrice")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HotelServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdHotelService")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceService")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HotelServiceId");

                    b.ToTable("HotelServicePrice");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.HotelService", b =>
                {
                    b.HasOne("HotelCalcApp.Model.Data.Hotel", null)
                        .WithMany("HotelServices")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.HotelServicePrice", b =>
                {
                    b.HasOne("HotelCalcApp.Model.Data.HotelService", null)
                        .WithMany("HotelServicePricesList")
                        .HasForeignKey("HotelServiceId");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.Hotel", b =>
                {
                    b.Navigation("HotelServices");
                });

            modelBuilder.Entity("HotelCalcApp.Model.Data.HotelService", b =>
                {
                    b.Navigation("HotelServicePricesList");
                });
#pragma warning restore 612, 618
        }
    }
}
